### ISSUE TITLE
New Competence: Interdisciplinary Communication

### ISSUE THREAD

**Issue by dokempf** [CaptainSifff/paper_teaching-learning-RSE#131]
Thanks for the great write up! While reading through the competencies list and comparing to my personal experience, I identified a gap that I would suggest to bridge: Skills in interdisciplinary communication are absolutely vital for RSEs in my experience. It might be slightly less so for RSEs that strictly work in one domain only, but it is of paramount importance for "central" RSEs that work with all disciplines. I would suggest to place this among the "Team" skills, although it also has some connection to research skills.

I can provide a PR with a preliminary draft.

**Comment by CaptainSifff** [comment]
I think it's in there, especially now, after we have improved on the TEAMS section in #115 (merged today). 
In case you want to emphasize it even more for decentralized RSE teams, have a look on the Project Team structures table. Since it's a double column layout, it takes on two viewpoints: RSE *teams* from a common RSE unit, or a *group* of RSEs which happen to work towards a common goal. Also the column, on how organizations can work towards the respective competencies might be of interest.

**Comment by CaptainSifff** [comment]
- the Example master now contains it.
- added two notes to the competency table.
