### ISSUE TITLE
Related Work - Criteria?

### ISSUE THREAD

**Issue by geyslein** [CaptainSifff/paper_teaching-learning-RSE#133]
When I was reading the list of related works of the foundational competencies part I was wondering if you have a criteria for the list or is it just a random selection?

I would suggest to add at least the [programming historian](https://programminghistorian.org/en/) to that list to add some humanities :book:  notion to the selection. If that's ok with you, I would add some text to that list.

Otherwise there is some more related work possible, e.g. compare with trainings listed here: [Awesome Educational Resources for Research Software Engineering](https://github.com/hifis-net/awesome-rse-education#trainings-and-courses)

**Comment by CaptainSifff** [comment]
noting this: #136

**Comment by CaptainSifff** [comment]
Doing A proper survey of existing resources is a good and necessary endevaour, but also is it's own paper. And that's why we have survey.md . Here we can survey the breadth of resources  in the necessary space. Although I'd like to point out, that the group so far thinks that it would be best done as a living document not as a tradtional paper. and probably as a GH pages thing, see #136 . For the competencies paper, we wanted to keep the survey of other resources to a politically acceptable minimum, although now already other things are mentioned: #135 . We have so far chosen to mention the big initiatives. With that in mind, feel free to contribute PRs to the respective paper.

**Comment by CaptainSifff** [comment]
The programminghistorian is at least in the survey paper coming in PR #101

**Comment by geyslein** [comment]
Cool, so I close the issue then.
