### ISSUE TITLE
More comments about Competencies Paper

### ISSUE THREAD

**Issue by annalenalamprecht** [CaptainSifff/paper_teaching-learning-RSE#242]
I would like to share some more thoughts and observations from a complete read of the competencies paper: 

- [x] 1.) Software Re-Use (SRU) is listed as a research skill, but it is actually one of the classical key SE/technical skill. Also its description is mainly technical and not very research-specific, so I wonder if it should be moved to the technical skills?
- [x] 2.) The Software Publication (SP) skill is mainly concerned with licences, but (open-source) licensing is not the same as software publication, and perhaps we should also talk about software citation here? @sdruskat, your input would be appreciated!
- [x] 3.) Minor thing in the same paragraph: "The second part of FAIR software is..." suggest that all is said about FAIR4RS after that, but actually there is much more to it. Quick fix could be to rephrase to "FAIR software is also concerned with ..."
- [x] 4.)For the DOMREP skill, I was wondering wether the difficult between repos (where software is developed) and registries/directories (places to find software) has been discussed? 
- [x] 5.)The TEAM section starts with a tautology: "Working in a team is all about [...] teamwork". Perhaps something like "Working in a team is essential for RSEs." would be sufficient?
- [x] 6.) The future work section mentions something about a "survey-publication", but from the paper I don't have any idea what this is referring to. Sounds like an internal comment to the team, that could probably be removed here.
- [x] 7.)A thought that popped up in my head when reading A.1 (foundational module), but perhaps it is more general: How relevant is object-oriented programming and design?

**Comment by BeastyBlacksmith** [comment]
> A thought that popped up in my head when reading A.1 (foundational module), but perhaps it is more general: How relevant is object-oriented programming and design?

Personally, I wouldn't enforce teaching it in the curriculum and leave it up to the teaching person. Surely it's good if RSEs know about it, in particular for dealing with existent software, but I don't see a reason to give it more prominence in the curriculum than any other programming paradigm.
In that regard a module about programming paradigms would make sense, but on the other hand I don't see A.1 as a full-fledged curriculum that should be used as is rather than a blueprint that one could use to craft a curriculum.

**Comment by fer-rum** [comment]
I would consider it good-to-know. Not extremely important, but not negligible.
The focus of the curriculum should be to illustrate what paradigms there are and how and when to use them.

As an example, I find that a lot of resource planning tasks - timetables, logistics … boil down to QSAT-problems that you can easily formulate _if_ you have enough of a grasp of logic programming to formulate a CNF. Feed it to a solver, translate the result to something human readable and bingo.

Instead I find people now trying to train exhaustive AIs for this kind of job, because they do miss the knowledge about other established paradigms that could have helped them (and run faster and consume way less energy and may deliver more accurate results).

---

The fundamental goal is to build a broad range of knowledge and ideally invest some time to playing around with these to build experience that can help to later make more informed decisions which ones to employ for a specific problem.

**Comment by sdruskat** [comment]
➕ 1️⃣  on not giving focus to one paradigm over others. (Personally I think that functional programming may be more relevant than OOP in some disciplines.)

And thanks for the ping @annalenalamprecht, I'll take look at the SP section.

**Comment by mhagdorn** [comment]
My sneaky suspicion is that a lot if not most code (I probably mean programs here) is very linear and not even procedural: you start at the top reading some data, do some analysis and visualise the results.

**Comment by sdruskat** [comment]
>     * The Software Publication (SP) skill is mainly concerned with licences, but (open-source) licensing is not the same as software publication, and perhaps we should also talk about software citation here? @sdruskat, your input would be appreciated!

See #243.

**Comment by CaptainSifff** [comment]
@annalenalamprecht to your second last point, with regard to the survey project: Now that @MakisH got the site up and running (Big Hug!)  I could integrate it with commit a7c9b21bf0186233b1223da1f0151a7d58a36a90  .

**Comment by CaptainSifff** [comment]
Iem two has been resolved by #243 .

**Comment by CaptainSifff** [comment]
Item (6) has been resolved with a7c9b21 .

**Comment by CaptainSifff** [comment]
item (5) has been  resolved in e151fa921a68129eedb2b717993128c8ce000fde

**Comment by CaptainSifff** [comment]
(3) has already been rephrased:
"Another part is given by..."
Determined by..." e151fa921a68129eedb2b717993128c8ce000fde

**Comment by CaptainSifff** [comment]
item 1) moved to #249

**Comment by CaptainSifff** [comment]
Item (4) has been moved to #250

**Comment by CaptainSifff** [comment]
From the comments above, I would infer that our community opinion here is, that we emphasize knowing multiple paradigms. I added a small sentence in cb11c32 to at least bring in the word *programming paradigm*.

**Comment by CaptainSifff** [comment]
Closing now, since all two points have been adressed. The remaining points are now in two separate sub-issues
