### ISSUE TITLE
Address sustainability within the planetary limits as an issue

### ISSUE THREAD

**Issue by CaptainSifff** [CaptainSifff/paper_teaching-learning-RSE#247]

**Comment by CaptainSifff** [comment]
Notifying @michelemartone

**Comment by mhagdorn** [comment]
some starting points
* scientists for future: https://doi.org/10.1126/science.aax3807
* planetary boundaries: https://doi.org/10.1126/sciadv.adh2458
* safe and just earth system boundaries, doughnut economy
* wikipedia on green computing: https://en.wikipedia.org/wiki/Green_computing
* green 500: https://www.top500.org/lists/green500/

**Comment by mhagdorn** [comment]
Digital science requires physical resources such as hardware and energy. An RSE needs to therefore also be aware of and consider planetary boundaries.

**Comment by michelemartone** [comment]
The last two decades saw the limits in the attainable miniaturization of transistor technology approaching, and top chip clock frequency mostly settled. [1]
Nevertheless, the perception in the popular culture remains fairly unaware of that, and a misleading belief into limitless growth of computing capabilities (storage, computing power, transmission speed) is still widespread.
A practical consequence of this is an ever-growing demand of resources to cover the expanded need for storage and processing, with no clear deceleration in sight (e.g. the IEA estimates a doubling in data centres energy consumption from 2024 to 2026 [2]).
At the same time, current science is well aware of several "planetary boundaries" being trespassed consequently to human activities [3], with this (computation and information) accounting for a non negligible fraction [2].
A reorientation of consumption into sustainable rates is being strived with great difficulty, despite repeated appeals from the sectors of society most knowledgeable on the matter [4].                                                                                      
In this scenario, RSEs have a responsibility, for instance when choosing computationally adequate approaches (e.g. recognizing where a well-proved statistical method may do well instead of a power-hungry AI model, or configuring a test pipeline to minimize redundancy), and embracing data frugality measures (e.g. recognizing "high enough" resolutions when sampling data for processing or storage), 
If past computational solutions were "frugal" because of technological limits, future ones should tend to that by virtue of an awareness of what "adequate" solutions may be.
To be helpful in these regards, RSEs may need basic skills in extrapolating energy, storage, and computational needs, resorting to expert knowledge for the details, and within regulatory frameworks yet to come.

 [1]  http://www.gotw.ca/publications/concurrency-ddj.htm
 [2]  https://www.iea.org/reports/electricity-2024
 [3]  https://doi.org/10.1126/sciadv.adh2458 ()
 [4]  https://doi.org/10.1126/science.aax3807

**Comment by michelemartone** [comment]
Hi @CaptainSifff. I've put it in a small section before Emerging Challenges. IMHO it's OK as standalone. Initial thoughts were of having it into an Values section, but that section is rather on adhering to existing rules or best practices, and much into delivering quality. Here the focus is on challenges of a larger scope, and to a large extent not yet fully tackled by society. @mhagdorn will do a quality check pass over this.

**Comment by mhagdorn** [comment]
we are right on topic
https://www.heise.de/news/Energiehungrige-Sprachmodelle-Ruf-nach-Leitplanken-fuer-gruene-KI-9682041.html

**Comment by mhagdorn** [comment]
find references on how to calculate footprint to teach and learn website

**Comment by mhagdorn** [comment]
added issue https://github.com/DE-RSE/learn-and-teach/issues/22 to learning and teaching repo
