### ISSUE TITLE
section on FAIR

### ISSUE THREAD

**Issue by mhagdorn** [CaptainSifff/paper_teaching-learning-RSE#55]
The term FAIR is used in a number of places. I think it would be worth to add a paragraph on FAIR somewhere in the introduction. Implementing FAIR principles requires RSEs, the two go hand in hand.

**Comment by CaptainSifff** [comment]
Good point, I had added FAIR4RS in MR #37  o what we define as research. It's currently mentioned in the small part on the Reprohack initative that I feel like removing as long as no-one elaborates it. And I don't think it is really teaching related. But we should have something in there since we use FAIR in the SD category.

**Comment by mhagdorn** [comment]
I have added merge request #56
