### ISSUE TITLE
Remove Academic Progression "skill-table"

### ISSUE THREAD

**Issue by hvwaldow** [CaptainSifff/paper_teaching-learning-RSE#66]
I feel we could gain from removing this:

https://github.com/CaptainSifff/paper_teaching-learning-RSE/blob/b1730a3b88104c8c85b938c989d8278676ffce0c/paper_teaching-learning-RSE.md?plain=1#L368-L408

1. If our focus is on education for RSEs, this is somewhat out of scope. RSEs by our definition is a job orthogonal to the academic degree scale.
2. So if we don't talk about RSEs here, but researchers with more or less RSE-type skills, I feel the classification into academic degrees makes little sense: You might have a technician, who is instrumental for some very sophisticated RSE-type job in a lab, you might have division of labor in a lab, where master student A does the software-dev internaional project stuff, whereas master student B specializes in the mass-spec facility, And that is ok. No need for B  to learn RSE-type skills.
3. The high redundancy in the table seems to support my point that this classification (academic degree scale) does not map nicely to RSE skills.

**Comment by jpthiele** [comment]
The initial workshop name was "Teaching and Learning RSE skills", 
which also encompasses non-RSE scientists in software heavy fields. 
I still think it would be worthwhile to keep in mind that courses, e.g. for an RSE master, 
can also be of interest to domain science students. 
But I also see your point that we should think about the usefulness of this table.
I think we should discuss this (again) after splitting the paper, because that 
might introduce a contextual change which emphasizes either your or the original point.

**Comment by mhagdorn** [comment]
As discussed at the meeting on 2023/08/25 I have reworded the academic progression section and table. I think it is a little more digestible now. Whether we want to keep it is another matter. Anyway, it's on the [replace-academic-progression](https://github.com/CaptainSifff/paper_teaching-learning-RSE/tree/replace-academic-progression) branch. Feel free to poke it.
