### ISSUE TITLE
Resources

### ISSUE THREAD

**Issue by CaptainSifff** [CaptainSifff/paper_teaching-learning-RSE#7]
We have the pad on resources:
https://pad.gwdg.de/teaching-RSE-resource-pad#

Any ideas on how to integrate it into the paper, or build another structure around it?

- We could integrate it into the deRSE webpresence maybe?

**Comment by jngrad** [comment]
I'm currently expanding the section on training materials to include these resources. It's a bit tricky because we have reference works on RSEng, training material for RSEs and training material for RSE trainers. Also, many of these resources are living documents that are version-controlled, so they don't come with a BibTeX file. We even have a living book and a living scientific paper in the list.

**Comment by jngrad** [comment]
Makes sense. I guess we can cite the institution that offers training (if they have a web presence or white paper), and also cite their training material main page, if different from their web presence. From what I've seen, all these automatically generated websites have a link to the main GitHub repository where the source material is, so that readers can access the raw material, if they so choose. I'm a bit hesitant about citing the repositories directly, since they don't always have a readme file, but we can discuss the details during the review. I'll try to open the PR this week.

I will in any case mention that training material often take the form of living documents, due to the ever-evolving nature of competencies and infrastructure in the RSE field. This is not something you see much in other fields like CS or STEM, where you typically get started by reading a printed copy of a reference textbook.
