### ISSUE TITLE
Sort out and collect masters program.

### ISSUE THREAD

**Issue by CaptainSifff** [CaptainSifff/paper_teaching-learning-RSE#97]
We now have existing masters programs all over the place.( #69,  #4 )
We need to collect and structure them somehow.

**Comment by CaptainSifff** [comment]
@tobyhodges

**Comment by MakisH** [comment]
Since the list is getting extensive, we should probably not aim for a wide overview, but for connecting and differentiating for those (and highlighting the additional value). Looking at the example curriculum appendix (#132), we could probably add a small paragraph there (but probably after merging).

**Comment by CaptainSifff** [comment]
The Masters programme that we have, also kind of follows this pattern. There I can imagine extending the introduction.

**Comment by MakisH** [comment]
Suggestion: Let's make this list a living document, transfer it in the deRSE website, and link to that page.

It is already helpful for people that want to study something related right now.

**Comment by CaptainSifff** [comment]
Another international HPC example:
https://mhpc.it/presentation
